name: "release"
on:
  workflow_dispatch:
  push:
    tags:
      - "*"
    branches:
      - "*"
    paths:
      - "**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  create-or-find-release:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'semantic-release-bot'
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    outputs:
      release_id: ${{ steps.set-release-id.outputs.release_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Find or create release
        id: set-release-id
        uses: actions/github-script@v6
        with:
          script: |
            const version = `v${process.env.PACKAGE_VERSION}`;
            const { data: releases } = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            let release = releases.find(r => r.tag_name === version);
            if (!release) {
              const { data } = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: version,
                name: version,
                body: '*This release was generated automatically using GitHub Actions.*',
                draft: true,
                prerelease: false
              });
              release = data;
            }
            return { release_id: release.id };

  build-tauri:
    needs: create-or-find-release
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: v2 -> v2/target

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache-dependency-path: v2/package-lock.json

      - name: Install apt dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt install -y --no-install-recommends libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Install bun in Windows
        if: matrix.platform == 'windows-latest'
        run: |
            iwr https://bun.sh/install.ps1 | iex
            echo "C:\Users\runneradmin\.bun\bin" >> $env:GITHUB_PATH

      - name: Verify Bun Installation
        if: matrix.platform == 'windows-latest'
        run: bun --version
        
      - name: Install bun in other platforms
        if: matrix.platform != 'windows-latest' 
        run: npm install -g bun

      - name: Install frontend dependencies
        run: bun install

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-or-find-release.outputs.release_id }}

      - name: Upload artifacts to release
        if: matrix.platform == 'ubuntu-latest'
        run: |
          assets=($(find ./src-tauri/target/release/bundle -type f))
          for asset in "${assets[@]}"; do
            gh release upload ${{ needs.create-or-find-release.outputs.release_id }} "$asset" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-20.04
    needs: [create-or-find-release, build-tauri]

    steps:
      - name: Publish release
        id: publish-release
        uses: actions/github-script@v6
        env:
          release_id: ${{ needs.create-or-find-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
